### ISSUE TITLE
Mockup - HOME (FRONTEND)

### ISSUE THREAD

**Issue by AlejaDeV** [FADEDevs/Hogar_Colombia#1]
Se debe diseñar un portal web, en el i) home se describe la inmobiliaria y se muestran solo los inmuebles activos para que sean visualizados de forma libre por todo el público mediante un filtro de alquiler o compra, ii) la misión, iii) la visión y iv) un formulario de contacto a través del cual se podrá ingresar un mensaje, los datos de la persona y un tipo de mensaje (compra o alquiler). Este mensaje será enviado al correo definido por el administrador en su perfil.

**Comment by JhoanLozano** [comment]
![Image](https://user-images.githubusercontent.com/110625678/198371776-69ff07fc-3a82-495c-83a4-d7be38f9db9c.png)
